name: Publish package

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  create-release:
    name: Create new release
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        uses: toitlang/pkg-publish@958688a194a7eafe38c62589b3de09f56e4206f1
